/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_cb_version                     16
#define gattdb_sw_version                     21
#define gattdb_device_information             24
#define gattdb_manufacturer_name_string       26
#define gattdb_system_id                      28
#define gattdb_primingSwitch                  31
#define gattdb_renaming_char                  36
#define gattdb_battery_Reading                41
#define gattdb_analog_Reading                 46
#define gattdb_TX_char                        51
#define gattdb_ota                            54
#define gattdb_ota_control                    56


#endif // __GATT_DB_H
